LoadModule coraza_module modules/mod_coraza.so

Coraza On
CorazaRulesFile /opt/coraza/config/coraza-rules.conf

ServerName ${SERVER_NAME}
ServerTokens ${SERVER_TOKENS}
KeepAliveTimeout ${KEEPALIVE_TIMEOUT}
ProxyTimeout ${PROXY_TIMEOUT}

ErrorLog ${ERRORLOG}
CustomLog ${ACCESSLOG} combined
LogLevel ${LOGLEVEL}

# Real IP (when behind a load balancer / reverse proxy)
RemoteIPHeader ${REMOTEIP_HEADER}
RemoteIPInternalProxy ${REMOTEIP_INT_PROXY}

Protocols ${H2_PROTOCOLS}

<VirtualHost *:${PORT}>
    # TLS redirect
    RewriteEngine On
    RewriteCond %{ENV:ALWAYS_TLS_REDIRECT} on
    RewriteRule ^(.*)$ https://%{SERVER_NAME}:${SSL_PORT}$1 [L,R=301]

    # Reverse proxy to backend
    ProxyPreserveHost On
    ProxyPass / http://${BACKEND}/
    ProxyPassReverse / http://${BACKEND}/
</VirtualHost>

<VirtualHost *:${SSL_PORT}>
    SSLEngine on
    SSLCertificateFile ${SSL_CERT_FILE}
    SSLCertificateKeyFile ${SSL_CERT_KEY_FILE}
    SSLProtocol ${SSL_PROTOCOLS}
    SSLCipherSuite ${SSL_CIPHERS}

    RequestHeader set X-Forwarded-Proto "https"

    # Reverse proxy to backend
    ProxyPreserveHost On
    ProxyPass / http://${BACKEND}/
    ProxyPassReverse / http://${BACKEND}/
</VirtualHost>
