LoadModule coraza_module modules/mod_coraza.so

Coraza On
CorazaRulesFile /opt/coraza/config/coraza-rules.conf

ServerName ${SERVER_NAME}
ServerTokens ${SERVER_TOKENS}
KeepAliveTimeout ${KEEPALIVE_TIMEOUT}
ProxyTimeout ${PROXY_TIMEOUT}

ErrorLog ${ERRORLOG}
CustomLog ${ACCESSLOG} combined
LogLevel ${LOGLEVEL}

<VirtualHost *:${PORT}>
    # Reverse proxy to backend
    ProxyPreserveHost On
    ProxyPass / http://${BACKEND}/
    ProxyPassReverse / http://${BACKEND}/
</VirtualHost>

<VirtualHost *:${SSL_PORT}>
    SSLEngine on
    SSLCertificateFile ${SSL_CERT_FILE}
    SSLCertificateKeyFile ${SSL_CERT_KEY_FILE}
    SSLProtocol ${SSL_PROTOCOLS}
    SSLCipherSuite ${SSL_CIPHERS}

    RequestHeader set X-Forwarded-Proto "https"

    # Reverse proxy to backend
    ProxyPreserveHost On
    ProxyPass / http://${BACKEND}/
    ProxyPassReverse / http://${BACKEND}/
</VirtualHost>
