# Main Coraza configuration
Include /opt/coraza/config/coraza.conf

# User defined configuration files
Include /opt/coraza/config.d/*.conf

# OWASP Core Rule Set (CRS) Setup
Include /opt/coraza/config/crs-setup.conf

Include /opt/coraza/owasp-crs/plugins/*-config.conf
Include /opt/coraza/owasp-crs/plugins/*-before.conf

# User plugins Setup
Include /opt/coraza/plugins/*-config.conf
Include /opt/coraza/plugins/*-before.conf

# OWASP Core Rule Set (CRS)
Include /opt/coraza/owasp-crs/rules/*.conf

Include /opt/coraza/owasp-crs/plugins/*-after.conf

# User plugins after
Include /opt/coraza/plugins/*-after.conf

# Other baked in rule sets or configurations
Include /opt/coraza/rules/*.conf

# User defined rule sets
Include /opt/coraza/rules.d/*.conf

# Any overrides specified in env vars
Include /opt/coraza/overrides/*.conf
