load_module "/usr/lib/nginx/modules/ngx_http_coraza_module.so";

worker_processes auto;

error_log ${ERRORLOG} ${LOGLEVEL};
pid /tmp/nginx.pid;

events {
    worker_connections ${WORKER_CONNECTIONS};
}

http {
    server_tokens ${SERVER_TOKENS};
    keepalive_timeout ${KEEPALIVE_TIMEOUT};

    coraza on;
    coraza_rules_file /opt/coraza/config/coraza-rules.conf;

    access_log ${ACCESSLOG};

    upstream backend {
        server ${BACKEND};
    }

    server {
        listen ${PORT} default_server;
        server_name ${SERVER_NAME};

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout ${PROXY_TIMEOUT};
            proxy_send_timeout ${PROXY_TIMEOUT};
            proxy_read_timeout ${PROXY_TIMEOUT};
        }
    }
}
